'use client';

import Link from 'next/link';
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Calendar, CheckSquare2, FilePlus2, Globe2, LoaderCircle, ReceiptText, Search, Square } from 'lucide-react';
import { useRouter } from 'next/navigation';
import styles from '../facturacion.module.css';

type Ticket={IdApertura:number;IdVenta:number;IdFactura?:number;IdSolicitud?:number;IdFacturaGlobal?:number;Folio:string;FechaVenta:string;Cliente:string;taxableConsumption:number;tip:number;fiscal:{base:number;iva:number;ieps:number}};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);

export default function NewInvoicePage(){
  const router=useRouter();const [date,setDate]=useState(today),[tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[mode,setMode]=useState<'cliente'|'publico_general'|'global'>('cliente'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const postal=useRef<HTMLInputElement>(null),adjusted=useRef(false);
  useEffect(()=>{if(postal.current)postal.current.value=localStorage.getItem('bretone-issuer-postal-code')||''},[]);
  useEffect(()=>{const timer=setTimeout(()=>{if(new URLSearchParams(window.location.search).get('modo')==='global')setMode('global')},0);return()=>clearTimeout(timer)},[]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/dashboard/facturacion?fecha=${date}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'No fue posible consultar los tickets');if(data.issuerPostalCode&&postal.current)postal.current.value=data.issuerPostalCode;if(!(data.tickets||[]).length&&data.latestDate&&!adjusted.current){adjusted.current=true;setDate(data.latestDate);return}setTickets((data.tickets||[]).filter((ticket:Ticket)=>!ticket.IdFactura&&!ticket.IdSolicitud&&!ticket.IdFacturaGlobal));setSelected(new Set())}catch(value){setError(value instanceof Error?value.message:'No fue posible consultar los tickets')}finally{setLoading(false)}},[date]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  const visible=useMemo(()=>tickets.filter(ticket=>!search||`${ticket.Folio} ${ticket.Cliente}`.toLowerCase().includes(search.toLowerCase())),[tickets,search]);
  const chosen=mode==='global'?tickets:tickets.filter(ticket=>selected.has(`${ticket.IdApertura}:${ticket.IdVenta}`));
  const totals=chosen.reduce((sum,ticket)=>({base:sum.base+ticket.fiscal.base,iva:sum.iva+ticket.fiscal.iva,ieps:sum.ieps+ticket.fiscal.ieps,consumption:sum.consumption+ticket.taxableConsumption,tips:sum.tips+ticket.tip}),{base:0,iva:0,ieps:0,consumption:0,tips:0});
  const allVisible=visible.length>0&&visible.every(ticket=>selected.has(`${ticket.IdApertura}:${ticket.IdVenta}`));
  function toggle(ticket:Ticket){const key=`${ticket.IdApertura}:${ticket.IdVenta}`;setSelected(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next})}
  function toggleAll(){setSelected(current=>{const next=new Set(current);for(const ticket of visible){const key=`${ticket.IdApertura}:${ticket.IdVenta}`;if(allVisible)next.delete(key);else next.add(key)}return next})}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(mode!=='global'&&!chosen.length){setError('Selecciona al menos un ticket');return}const cp=postal.current?.value||'';if(!/^\d{5}$/.test(cp)){setError('Captura el C.P. de expedición');return}setSaving(true);setError('');try{const form=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch('/api/dashboard/facturacion/facturas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,mode,fecha:date,codigoPostalExpedicion:cp,tickets:chosen.map(ticket=>({idApertura:ticket.IdApertura,idVenta:ticket.IdVenta}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No fue posible crear la factura');localStorage.setItem('bretone-issuer-postal-code',cp);router.push('/dashboard/facturacion')}catch(value){setError(value instanceof Error?value.message:'No fue posible crear la factura')}finally{setSaving(false)}}

  return <div className={styles.page}><header className={styles.header}><div><Link className={styles.back} href="/dashboard/facturacion"><ArrowLeft/>Facturas realizadas</Link><h1>Nueva factura</h1><p>Selecciona uno o varios tickets y revisa los impuestos antes de crearla.</p></div><div className={styles.headerControls}><label className={styles.postal}>C.P. de expedición<input ref={postal} inputMode="numeric" maxLength={5} placeholder="00000" onChange={e=>{e.currentTarget.value=e.currentTarget.value.replace(/\D/g,'').slice(0,5)}}/></label><label className={styles.date}><Calendar/><input type="date" value={date} onChange={e=>{adjusted.current=true;setDate(e.target.value)}}/></label></div></header>
    <div className={styles.composer}><section className={styles.ticketPicker}><div className={styles.modeTabs}><button className={mode==='cliente'?styles.modeActive:''} onClick={()=>setMode('cliente')}><FilePlus2/>Cliente</button><button className={mode==='publico_general'?styles.modeActive:''} onClick={()=>setMode('publico_general')}><ReceiptText/>Público general</button><button className={mode==='global'?styles.modeActive:''} onClick={()=>setMode('global')}><Globe2/>Global diaria</button></div><div className={styles.pickerToolbar}><div className={styles.search}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar ticket o cliente"/></div>{mode!=='global'&&<button className={styles.selectAll} onClick={toggleAll}>{allVisible?<CheckSquare2/>:<Square/>}{allVisible?'Quitar visibles':'Seleccionar visibles'}</button>}</div>{mode==='global'&&<div className={styles.globalInfo}><Globe2/><div><strong>Se incluirán todos los tickets disponibles del día</strong><p>Los tickets facturados individualmente o asignados a otra factura quedan excluidos.</p></div></div>}{loading?<div className={styles.empty}><LoaderCircle className={styles.spin}/>Consultando tickets…</div>:visible.length===0?<div className={styles.empty}><ReceiptText/><h2>No hay tickets disponibles</h2></div>:<div className={styles.ticketList}>{visible.map(ticket=>{const key=`${ticket.IdApertura}:${ticket.IdVenta}`,checked=mode==='global'||selected.has(key);return <button type="button" key={key} className={`${styles.ticketOption} ${checked?styles.ticketSelected:''}`} onClick={()=>mode!=='global'&&toggle(ticket)}><span className={styles.checkbox}>{checked?<CheckSquare2/>:<Square/>}</span><span><strong>{ticket.Folio}</strong><small>{new Date(ticket.FechaVenta).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})} · {ticket.Cliente}</small></span><span className={styles.ticketTaxes}><small>Base {money(ticket.fiscal.base)} · IVA {money(ticket.fiscal.iva)} · IEPS {money(ticket.fiscal.ieps)}</small><strong>{money(ticket.taxableConsumption)}</strong></span></button>})}</div>}</section>
      <form className={styles.invoiceComposer} onSubmit={create}><div className={styles.composerHead}><span>{mode==='global'?'Factura global diaria':mode==='publico_general'?'Factura a público general':'Factura de cliente'}</span><strong>{chosen.length} ticket{chosen.length===1?'':'s'}</strong></div><div className={styles.composerTotals}><div><span>Base</span><strong>{money(totals.base)}</strong></div><div><span>IVA</span><strong>{money(totals.iva)}</strong></div><div><span>IEPS</span><strong>{money(totals.ieps)}</strong></div><div className={styles.composerTotal}><span>Consumo facturable</span><strong>{money(totals.consumption)}</strong></div><small>Propinas excluidas: {money(totals.tips)}</small></div>{mode==='cliente'&&<div className={styles.fiscalForm}><label>RFC<input name="rfc" required maxLength={13}/></label><label>Nombre o razón social<input name="razonSocial" required/></label><div><label>C.P. fiscal<input name="codigoPostalFiscal" required pattern="\d{5}" maxLength={5}/></label><label>Régimen<select name="regimenFiscal" required defaultValue=""><option value="" disabled>Selecciona</option><option value="601">601 · General de Ley PM</option><option value="603">603 · PM sin fines de lucro</option><option value="605">605 · Sueldos y salarios</option><option value="606">606 · Arrendamiento</option><option value="612">612 · Actividad empresarial</option><option value="616">616 · Sin obligaciones</option><option value="625">625 · RESICO</option></select></label></div><div><label>Uso CFDI<select name="usoCFDI" required defaultValue="G03"><option value="G03">G03 · Gastos en general</option><option value="G01">G01 · Adquisición</option><option value="S01">S01 · Sin efectos fiscales</option></select></label><label>Correo<input name="correo" type="email"/></label></div></div>}{error&&<div className={styles.formError}>{error}</div>}<button className={styles.createButton} disabled={saving||!chosen.length}>{saving?<LoaderCircle className={styles.spin}/>:mode==='global'?<Globe2/>:<FilePlus2/>}{mode==='global'?'Generar global diaria':'Crear factura'}</button><p className={styles.pendingNote}>La factura se guardará como “Por timbrar” y podrá cancelarse mientras no tenga UUID.</p></form>
    </div></div>
}
