'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Ban, CalendarRange, ChevronDown, ChevronRight, FileCheck2, FileCode2, FileDown, FilePlus2, Globe2, LoaderCircle, Mail, ReceiptText, RefreshCw, Search, Send, Stamp, TriangleAlert, X } from 'lucide-react';
import styles from './facturacion.module.css';

type InvoiceTicket={IdApertura:number;IdVenta:number;Folio:string;FechaVenta:string;BaseGravable:number;IVA:number;IEPS:number;ConsumoFacturable:number;Propina:number};
type Invoice={IdFactura:number;Tipo:'cliente'|'publico_general'|'global';FechaOperacion:string;RFC:string;RazonSocial:string;Correo:string|null;NumTickets:number;BaseGravable:number;IVA:number;IEPS:number;ConsumoFacturable:number;Propinas:number;Estado:'pendiente_timbrado'|'timbrada'|'cancelada';UUID?:string;Serie?:string|null;Folio?:string|null;TotalTimbrado?:number|null;ErrorTimbrado?:string|null;TimbradaEn?:string|null;CreadaEn:string;CanceladaEn?:string;MotivoCancelacion?:string;tickets:InvoiceTicket[]};
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);
const dateValue=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const errorText=(error:unknown)=>error instanceof Error?error.message:'No fue posible completar la operación';
const invoiceCode=(invoice:Invoice)=>`F-${String(invoice.IdFactura).padStart(6,'0')}`;
const documentUrl=(idFactura:number,kind:'pdf'|'xml')=>`/api/dashboard/facturacion/documentos/${idFactura}?tipo=${kind}`;

export default function InvoicesPage(){
  const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1);
  const [from,setFrom]=useState(()=>dateValue(monthStart)),[to,setTo]=useState(()=>dateValue(now)),[invoices,setInvoices]=useState<Invoice[]>([]);
  const [search,setSearch]=useState(''),[status,setStatus]=useState<'all'|'pending'|'stamped'|'cancelled'>('all'),[expanded,setExpanded]=useState(0);
  const [loading,setLoading]=useState(true),[notice,setNotice]=useState<{type:'ok'|'error';text:string}|null>(null),[cancelInvoice,setCancelInvoice]=useState<Invoice|null>(null),[cancelling,setCancelling]=useState(false);
  const [stampInvoice,setStampInvoice]=useState<Invoice|null>(null),[stamping,setStamping]=useState(false),[mailInvoice,setMailInvoice]=useState<Invoice|null>(null),[sending,setSending]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch(`/api/dashboard/facturacion/facturas?from=${from}&to=${to}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'No fue posible consultar las facturas');setInvoices(data.invoices||[])}catch(error){setNotice({type:'error',text:errorText(error)})}finally{setLoading(false)}},[from,to]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  const visible=useMemo(()=>invoices.filter(invoice=>{const q=search.toLowerCase();const match=!q||`${invoiceCode(invoice)} ${invoice.RFC} ${invoice.RazonSocial} ${invoice.UUID||''}`.toLowerCase().includes(q);const state=status==='all'||(status==='pending'&&invoice.Estado==='pendiente_timbrado')||(status==='stamped'&&invoice.Estado==='timbrada')||(status==='cancelled'&&invoice.Estado==='cancelada');return match&&state}),[invoices,search,status]);
  const totals=useMemo(()=>invoices.filter(i=>i.Estado!=='cancelada').reduce((sum,i)=>({amount:sum.amount+Number(i.ConsumoFacturable),pending:sum.pending+(i.Estado==='pendiente_timbrado'?1:0),stamped:sum.stamped+(i.Estado==='timbrada'?1:0)}),{amount:0,pending:0,stamped:0}),[invoices]);
  async function cancel(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!cancelInvoice)return;setCancelling(true);try{const motivo=String(new FormData(event.currentTarget).get('motivo')||'');const response=await fetch('/api/dashboard/facturacion/facturas',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({idFactura:cancelInvoice.IdFactura,motivo})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No fue posible cancelar la factura');setNotice({type:'ok',text:data.message});setCancelInvoice(null);await load()}catch(error){setNotice({type:'error',text:errorText(error)})}finally{setCancelling(false)}}
  async function stamp(){if(!stampInvoice)return;setStamping(true);try{const response=await fetch('/api/dashboard/facturacion/timbrar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idFactura:stampInvoice.IdFactura})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No fue posible timbrar la factura');setNotice({type:'ok',text:[data.message,...(data.warnings||[])].join(' · ')});setStampInvoice(null);await load()}catch(error){setNotice({type:'error',text:errorText(error)})}finally{setStamping(false)}}
  async function sendMail(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!mailInvoice)return;setSending(true);try{const form=new FormData(event.currentTarget);const response=await fetch('/api/dashboard/facturacion/enviar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idFactura:mailInvoice.IdFactura,correo:String(form.get('correo')||''),mensaje:String(form.get('mensaje')||'')})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No fue posible enviar la factura');setNotice({type:'ok',text:data.message});setMailInvoice(null);await load()}catch(error){setNotice({type:'error',text:errorText(error)})}finally{setSending(false)}}

  return <div className={styles.page}>
    <header className={styles.header}><div><div className={styles.kicker}><FileCheck2/>Registro fiscal</div><h1>Facturas realizadas</h1><p>Timbra ante el SAT, consulta el PDF y el XML resguardados, y envíalos por correo.</p></div><div className={styles.headerActions}><Link className={styles.secondaryAction} href="/dashboard/facturacion/nueva?modo=global"><Globe2/>Global por día</Link><Link className={styles.primaryAction} href="/dashboard/facturacion/nueva"><FilePlus2/>Nueva factura</Link></div></header>
    <section className={styles.summary}><div><span>Facturado en el periodo</span><strong>{money(totals.amount)}</strong></div><div><span>Facturas</span><strong>{invoices.filter(i=>i.Estado!=='cancelada').length}</strong></div><div><span>Por timbrar</span><strong>{totals.pending}</strong></div><div><span>Timbradas</span><strong>{totals.stamped}</strong></div></section>
    {notice&&<div className={notice.type==='ok'?styles.noticeOk:styles.noticeError}>{notice.text}<button onClick={()=>setNotice(null)}><X/></button></div>}
    <section className={styles.panel}><div className={styles.toolbar}><div className={styles.range}><CalendarRange/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>a</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button onClick={load}><RefreshCw/></button></div><div className={styles.search}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar folio, RFC, receptor o UUID"/></div><div className={styles.filters}>{(['all','pending','stamped','cancelled'] as const).map(value=><button key={value} className={status===value?styles.activeFilter:''} onClick={()=>setStatus(value)}>{value==='all'?'Todas':value==='pending'?'Por timbrar':value==='stamped'?'Timbradas':'Canceladas'}</button>)}</div></div>
      {loading?<div className={styles.empty}><LoaderCircle className={styles.spin}/>Consultando facturas…</div>:visible.length===0?<div className={styles.empty}><ReceiptText/><h2>No hay facturas en este periodo</h2><p>Crea una factura seleccionando uno o varios tickets.</p><Link href="/dashboard/facturacion/nueva">Nueva factura</Link></div>:<div className={styles.tableWrap}><table className={styles.invoiceTable}><thead><tr><th/><th>Folio</th><th>Fecha</th><th>Tipo</th><th>Receptor</th><th>Tickets</th><th className={styles.number}>Base</th><th className={styles.number}>IVA</th><th className={styles.number}>IEPS</th><th className={styles.number}>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map(invoice=><InvoiceRows key={invoice.IdFactura} invoice={invoice} expanded={expanded===invoice.IdFactura} toggle={()=>setExpanded(expanded===invoice.IdFactura?0:invoice.IdFactura)} cancel={()=>setCancelInvoice(invoice)} stamp={()=>setStampInvoice(invoice)} mail={()=>setMailInvoice(invoice)}/>)}</tbody></table></div>}
    </section>
    {cancelInvoice&&<div className={styles.overlay} onMouseDown={()=>setCancelInvoice(null)}><form className={styles.cancelModal} onSubmit={cancel} onMouseDown={e=>e.stopPropagation()}><div className={styles.modalIcon}><Ban/></div><h2>Cancelar {invoiceCode(cancelInvoice)}</h2><p>La factura aún no está timbrada. Al cancelarla, sus {cancelInvoice.NumTickets} tickets volverán a estar disponibles.</p><label>Motivo de cancelación<textarea name="motivo" required minLength={5} defaultValue="Corrección antes de timbrado"/></label><div className={styles.modalActions}><button type="button" onClick={()=>setCancelInvoice(null)}>Conservar factura</button><button className={styles.danger} disabled={cancelling}>{cancelling?<LoaderCircle className={styles.spin}/>:<Ban/>}Cancelar y liberar tickets</button></div></form></div>}
    {stampInvoice&&<div className={styles.overlay} onMouseDown={()=>!stamping&&setStampInvoice(null)}><div className={styles.cancelModal} onMouseDown={e=>e.stopPropagation()}><div className={styles.stampIcon}><Stamp/></div><h2>Timbrar {invoiceCode(stampInvoice)}</h2><p>Se generará el CFDI 4.0 ante el SAT por <strong>{money(stampInvoice.ConsumoFacturable)}</strong> a nombre de {stampInvoice.RazonSocial} ({stampInvoice.RFC}), con {stampInvoice.NumTickets} ticket{stampInvoice.NumTickets===1?'':'s'}.</p><div className={styles.stampWarning}><TriangleAlert/><span>El timbrado consume un folio del PAC y no puede deshacerse desde aquí: un CFDI timbrado solo se cancela ante el SAT.{stampInvoice.Correo?` Al terminar se enviará automáticamente a ${stampInvoice.Correo}.`:''}</span></div>{stampInvoice.ErrorTimbrado&&<div className={styles.formError}>Último intento: {stampInvoice.ErrorTimbrado}</div>}<div className={styles.modalActions}><button type="button" onClick={()=>setStampInvoice(null)} disabled={stamping}>Regresar</button><button className={styles.confirmStamp} onClick={stamp} disabled={stamping}>{stamping?<LoaderCircle className={styles.spin}/>:<Stamp/>}{stamping?'Timbrando…':'Timbrar ante el SAT'}</button></div></div></div>}
    {mailInvoice&&<div className={styles.overlay} onMouseDown={()=>!sending&&setMailInvoice(null)}><form className={styles.cancelModal} onSubmit={sendMail} onMouseDown={e=>e.stopPropagation()}><div className={styles.stampIcon}><Mail/></div><h2>Enviar {invoiceCode(mailInvoice)}</h2><p>El PAC enviará el PDF y el XML timbrados al correo que indiques.</p><label>Correo del receptor<input name="correo" type="email" required defaultValue={mailInvoice.Correo||''} placeholder="cliente@correo.com"/></label><label>Mensaje<textarea name="mensaje" maxLength={500} defaultValue={`Adjuntamos tu factura ${invoiceCode(mailInvoice)}. Gracias por tu visita.`}/></label><div className={styles.modalActions}><button type="button" onClick={()=>setMailInvoice(null)} disabled={sending}>Cerrar</button><button className={styles.confirmStamp} disabled={sending}>{sending?<LoaderCircle className={styles.spin}/>:<Send/>}Enviar factura</button></div></form></div>}
  </div>
}

function InvoiceRows({invoice,expanded,toggle,cancel,stamp,mail}:{invoice:Invoice;expanded:boolean;toggle:()=>void;cancel:()=>void;stamp:()=>void;mail:()=>void}){
  const type=invoice.Tipo==='global'?'Global diaria':invoice.Tipo==='publico_general'?'Público general':'Cliente';
  const stamped=invoice.Estado==='timbrada'&&Boolean(invoice.UUID);
  return <><tr className={invoice.Estado==='cancelada'?styles.cancelledRow:''}><td><button className={styles.expand} onClick={toggle}>{expanded?<ChevronDown/>:<ChevronRight/>}</button></td><td><strong>{invoiceCode(invoice)}</strong>{invoice.Serie&&<small>CFDI {invoice.Serie}{invoice.Folio||invoice.IdFactura}</small>}{invoice.UUID&&<small>{invoice.UUID}</small>}</td><td>{new Date(`${String(invoice.FechaOperacion).slice(0,10)}T12:00:00`).toLocaleDateString('es-MX')}</td><td>{type}</td><td><strong>{invoice.RazonSocial}</strong><small>{invoice.RFC}</small></td><td>{invoice.NumTickets}</td><td className={styles.number}>{money(invoice.BaseGravable)}</td><td className={styles.number}>{money(invoice.IVA)}</td><td className={styles.number}>{money(invoice.IEPS)}</td><td className={styles.number}><strong>{money(invoice.TotalTimbrado??invoice.ConsumoFacturable)}</strong></td><td><span className={`${styles.status} ${stamped?styles.stamped:invoice.Estado==='cancelada'?styles.cancelled:styles.pending}`}>{stamped?'Timbrada':invoice.Estado==='cancelada'?'Cancelada':'Por timbrar'}</span></td>
    <td><div className={styles.rowActions}>
      {invoice.Estado==='pendiente_timbrado'&&!invoice.UUID&&<><button className={styles.stampButton} onClick={stamp}><Stamp/>Timbrar</button><button className={styles.cancelButton} onClick={cancel}><Ban/>Cancelar</button></>}
      {stamped&&<><a className={styles.docButton} href={documentUrl(invoice.IdFactura,'pdf')} target="_blank" rel="noreferrer"><FileDown/>PDF</a><a className={styles.docButton} href={documentUrl(invoice.IdFactura,'xml')} target="_blank" rel="noreferrer"><FileCode2/>XML</a><button className={styles.docButton} onClick={mail}><Mail/>Enviar</button></>}
    </div></td></tr>
    {expanded&&<tr className={styles.invoiceDetail}><td colSpan={12}><div>
      {stamped&&<div className={styles.cfdiBox}><div><span>Folio fiscal (UUID)</span><strong>{invoice.UUID}</strong></div><div><span>Timbrada el</span><strong>{invoice.TimbradaEn?new Date(invoice.TimbradaEn).toLocaleString('es-MX'):'—'}</strong></div><div><span>Total timbrado</span><strong>{money(invoice.TotalTimbrado??invoice.ConsumoFacturable)}</strong></div><div className={styles.cfdiLinks}><a href={documentUrl(invoice.IdFactura,'pdf')} target="_blank" rel="noreferrer"><FileDown/>Descargar PDF</a><a href={documentUrl(invoice.IdFactura,'xml')} target="_blank" rel="noreferrer"><FileCode2/>Descargar XML</a></div></div>}
      {!stamped&&invoice.ErrorTimbrado&&<div className={styles.stampWarning}><TriangleAlert/><span>Último intento de timbrado: {invoice.ErrorTimbrado}</span></div>}
      <div className={styles.detailHeader}><strong>Tickets de la factura</strong><span>Propinas fuera del importe facturable: {money(invoice.Propinas)}</span></div><table><thead><tr><th>Ticket</th><th>Fecha</th><th className={styles.number}>Base</th><th className={styles.number}>IVA</th><th className={styles.number}>IEPS</th><th className={styles.number}>Consumo</th><th className={styles.number}>Propina</th></tr></thead><tbody>{invoice.tickets.map(ticket=><tr key={`${ticket.IdApertura}-${ticket.IdVenta}`}><td>{ticket.Folio}</td><td>{new Date(ticket.FechaVenta).toLocaleString('es-MX')}</td><td className={styles.number}>{money(ticket.BaseGravable)}</td><td className={styles.number}>{money(ticket.IVA)}</td><td className={styles.number}>{money(ticket.IEPS)}</td><td className={styles.number}>{money(ticket.ConsumoFacturable)}</td><td className={styles.number}>{money(ticket.Propina)}</td></tr>)}</tbody></table>{invoice.Estado==='cancelada'&&<p className={styles.cancelReason}>Motivo: {invoice.MotivoCancelacion}</p>}
    </div></td></tr>}</>
}
