CREATE TABLE IF NOT EXISTS tblFacturasDashboard (
  IdFactura BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Tipo ENUM('cliente','publico_general','global') NOT NULL,
  FechaOperacion DATE NOT NULL,
  RFC VARCHAR(13) NOT NULL,
  RazonSocial VARCHAR(254) NOT NULL,
  CodigoPostal VARCHAR(5) NOT NULL,
  RegimenFiscal VARCHAR(3) NOT NULL,
  UsoCFDI VARCHAR(3) NOT NULL,
  Correo VARCHAR(254) NULL,
  Periodicidad VARCHAR(2) NULL,
  Meses VARCHAR(2) NULL,
  Anio SMALLINT NULL,
  NumTickets INT NOT NULL,
  BaseGravable DECIMAL(12,2) NOT NULL,
  IVA DECIMAL(12,2) NOT NULL,
  IEPS DECIMAL(12,2) NOT NULL,
  ConsumoFacturable DECIMAL(12,2) NOT NULL,
  Propinas DECIMAL(12,2) NOT NULL,
  Estado ENUM('pendiente_timbrado','timbrada','cancelada') NOT NULL DEFAULT 'pendiente_timbrado',
  UUID VARCHAR(36) NULL,
  CreadaEn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TimbradaEn DATETIME NULL,
  CanceladaEn DATETIME NULL,
  MotivoCancelacion VARCHAR(254) NULL,
  PRIMARY KEY (IdFactura),
  KEY idx_facturas_fecha (FechaOperacion, Estado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tblFacturaTicketsDashboard (
  IdFactura BIGINT UNSIGNED NOT NULL,
  IdApertura INT NOT NULL,
  IdVenta INT NOT NULL,
  Folio VARCHAR(32) NOT NULL,
  FechaVenta DATETIME NOT NULL,
  BaseGravable DECIMAL(12,2) NOT NULL,
  IVA DECIMAL(12,2) NOT NULL,
  IEPS DECIMAL(12,2) NOT NULL,
  ConsumoFacturable DECIMAL(12,2) NOT NULL,
  Propina DECIMAL(12,2) NOT NULL,
  AsignacionActiva TINYINT NULL DEFAULT 1,
  PRIMARY KEY (IdFactura, IdApertura, IdVenta),
  UNIQUE KEY uq_ticket_factura_activa (IdApertura, IdVenta, AsignacionActiva),
  KEY idx_factura_ticket (IdFactura)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
